// Copyright 2021 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go_gapic. DO NOT EDIT.

package test

import (
	"context"

	run "github.com/cristian-radu/cloud-run-grpc-client/pkg/client"
	runpb "github.com/cristian-radu/cloud-run-grpc-client/pkg/pb/run"
)

func ExampleNewConfigurationsClient() {
	ctx := context.Background()
	c, err := run.NewConfigurationsClient(ctx)
	if err != nil {
		// TODO: Handle error.
	}
	defer c.Close()

	// TODO: Use client.
	_ = c
}

func ExampleConfigurationsClient_GetConfiguration() {
	ctx := context.Background()
	c, err := run.NewConfigurationsClient(ctx)
	if err != nil {
		// TODO: Handle error.
	}
	defer c.Close()

	req := &runpb.GetConfigurationRequest{
		// TODO: Fill request struct fields.
	}
	resp, err := c.GetConfiguration(ctx, req)
	if err != nil {
		// TODO: Handle error.
	}
	// TODO: Use resp.
	_ = resp
}

func ExampleConfigurationsClient_ListConfigurations() {
	ctx := context.Background()
	c, err := run.NewConfigurationsClient(ctx)
	if err != nil {
		// TODO: Handle error.
	}
	defer c.Close()

	req := &runpb.ListConfigurationsRequest{
		// TODO: Fill request struct fields.
	}
	resp, err := c.ListConfigurations(ctx, req)
	if err != nil {
		// TODO: Handle error.
	}
	// TODO: Use resp.
	_ = resp
}
