// Copyright 2021 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go_gapic. DO NOT EDIT.

package test

import (
	"context"

	run "github.com/cristian-radu/cloud-run-grpc/pkg/client"
	pb "github.com/cristian-radu/cloud-run-grpc/pkg/pb"
)

func ExampleNewDomainMappingsClient() {
	ctx := context.Background()
	c, err := run.NewDomainMappingsClient(ctx)
	if err != nil {
		// TODO: Handle error.
	}
	defer c.Close()

	// TODO: Use client.
	_ = c
}

func ExampleDomainMappingsClient_CreateDomainMapping() {
	ctx := context.Background()
	c, err := run.NewDomainMappingsClient(ctx)
	if err != nil {
		// TODO: Handle error.
	}
	defer c.Close()

	req := &pb.CreateDomainMappingRequest{
		// TODO: Fill request struct fields.
	}
	resp, err := c.CreateDomainMapping(ctx, req)
	if err != nil {
		// TODO: Handle error.
	}
	// TODO: Use resp.
	_ = resp
}

func ExampleDomainMappingsClient_DeleteDomainMapping() {
	ctx := context.Background()
	c, err := run.NewDomainMappingsClient(ctx)
	if err != nil {
		// TODO: Handle error.
	}
	defer c.Close()

	req := &pb.DeleteDomainMappingRequest{
		// TODO: Fill request struct fields.
	}
	resp, err := c.DeleteDomainMapping(ctx, req)
	if err != nil {
		// TODO: Handle error.
	}
	// TODO: Use resp.
	_ = resp
}

func ExampleDomainMappingsClient_GetDomainMapping() {
	ctx := context.Background()
	c, err := run.NewDomainMappingsClient(ctx)
	if err != nil {
		// TODO: Handle error.
	}
	defer c.Close()

	req := &pb.GetDomainMappingRequest{
		// TODO: Fill request struct fields.
	}
	resp, err := c.GetDomainMapping(ctx, req)
	if err != nil {
		// TODO: Handle error.
	}
	// TODO: Use resp.
	_ = resp
}

func ExampleDomainMappingsClient_ListDomainMappings() {
	ctx := context.Background()
	c, err := run.NewDomainMappingsClient(ctx)
	if err != nil {
		// TODO: Handle error.
	}
	defer c.Close()

	req := &pb.ListDomainMappingsRequest{
		// TODO: Fill request struct fields.
	}
	resp, err := c.ListDomainMappings(ctx, req)
	if err != nil {
		// TODO: Handle error.
	}
	// TODO: Use resp.
	_ = resp
}
